name: release

on:
    release:
        types: [created]

jobs:
    package:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Use Node.js 14.15.4
              uses: actions/setup-node@v1
              with:
                  node-version: 14.15.4
                  registry-url: "https://registry.npmjs.org"

            - run: yarn
            - run: yarn build
            - run: yarn publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
